//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApp.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Devices : global::System.Configuration.ApplicationSettingsBase {
        
        private static Devices defaultInstance = ((Devices)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Devices())));
        
        public static Devices Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SysLogInUse {
            get {
                return ((bool)(this["SysLogInUse"]));
            }
            set {
                this["SysLogInUse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string SysLogHost {
            get {
                return ((string)(this["SysLogHost"]));
            }
            set {
                this["SysLogHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6514")]
        public int SysLogPort {
            get {
                return ((int)(this["SysLogPort"]));
            }
            set {
                this["SysLogPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1252")]
        public int SysLogEncoding {
            get {
                return ((int)(this["SysLogEncoding"]));
            }
            set {
                this["SysLogEncoding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<%syslog-priority>1 %utcdate{yyyy-MM-ddTHH:mm:ss.FFZ} %syslog-hostname %syslog-do" +
            "mainname %appdomain %syslog-process-id %syslog-message-id %syslog-structured-dat" +
            "a %message%newline%exception")]
        public string SysLogLayout {
            get {
                return ((string)(this["SysLogLayout"]));
            }
            set {
                this["SysLogLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public string SysLogFacilityCode {
            get {
                return ((string)(this["SysLogFacilityCode"]));
            }
            set {
                this["SysLogFacilityCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("example@32473")]
        public string SysLogStructuredDataPrefix {
            get {
                return ((string)(this["SysLogStructuredDataPrefix"]));
            }
            set {
                this["SysLogStructuredDataPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SysLogPrependMessageLength {
            get {
                return ((bool)(this["SysLogPrependMessageLength"]));
            }
            set {
                this["SysLogPrependMessageLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SysLogEntryFirstLineOnly {
            get {
                return ((bool)(this["SysLogEntryFirstLineOnly"]));
            }
            set {
                this["SysLogEntryFirstLineOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Off")]
        public global::DemoApp.Config.Log4NetLogLevel SysLogSendLogsLevelMin {
            get {
                return ((global::DemoApp.Config.Log4NetLogLevel)(this["SysLogSendLogsLevelMin"]));
            }
            set {
                this["SysLogSendLogsLevelMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Off")]
        public global::DemoApp.Config.Log4NetLogLevel SysLogSendLogsLevelMax {
            get {
                return ((global::DemoApp.Config.Log4NetLogLevel)(this["SysLogSendLogsLevelMax"]));
            }
            set {
                this["SysLogSendLogsLevelMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tcp")]
        public global::DemoApp.Config.SysLogProtocol SysLogProtocol {
            get {
                return ((global::DemoApp.Config.SysLogProtocol)(this["SysLogProtocol"]));
            }
            set {
                this["SysLogProtocol"] = value;
            }
        }
    }
}
